version: '3.8'

services:
  web:
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_NAME=resume_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - .env

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=resume_db
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d resume_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=22bcaf07@kristujayanti.com
      - PGADMIN_DEFAULT_PASSWORD=ADMIN  # Replace with a secure password
    ports:
      - "5055:80"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: